apps/article/urls.py
from django.urls import path
from . import views


app_name = 'article'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('info/', views.InfoView.as_view(), name='info'),
    path('study/<name>', views.StudyView.as_view(), name='study'),
]


apps/life/urls.py
from django.urls import path
from . import views


app_name = 'life'
urlpatterns = [
    path('time/', views.time, name='time'),
    path('about/', views.about, name='about'),
    path('message/', views.Message.as_view(), name='message'),
]


lublog/urls.py
import xadmin
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', xadmin.site.urls),  # 后台管理界面插件
    path('mdeditor/', include('mdeditor.urls')),  # markdown插件
    path('users/', include('users.urls')),
    path('', include('article.urls')),
    path('', include('verifications.urls')),
    path('lifes/', include('life.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/article/models.py
# article/models.py
import markdown

from users.models import Users
from mdeditor.fields import MDTextField
from django.db import models
from mptt.models import MPTTModel
from django.shortcuts import reverse  # 查找URL
from utils.basemodel import ModelBase


class BigCategory(models.Model):
    # 导航名称
    name = models.CharField(verbose_name='导航分类', max_length=20)
    # 分类栏目页描述
    description = models.TextField(verbose_name='描述', max_length=240, )
    class Meta:  # 元信息
        verbose_name = '一级导航'
        verbose_name_plural = verbose_name  # 复数形式相同

    def __str__(self):
        return self.name


# 导航菜单分类下的下拉菜单分类
class Category(models.Model):
    # 分类名字
    name = models.CharField(verbose_name='文章分类', max_length=20)
    # 导航菜单一对多二级菜单,django2.0后定义外键和一对一关系的时候需要加on_delete选项，此参数为了避免两个表里的数据不一致问题
    bigcategory = models.ForeignKey(to=BigCategory, on_delete=models.CASCADE, verbose_name='大分类')

    class Meta:  # 元信息
        verbose_name = '二级导航'
        verbose_name_plural = verbose_name
        # 默认排序
        ordering = ['name']

    def __str__(self):
        return self.name


# 文章标签
class Tag(models.Model):
    """
    文章标签
    """
    name = models.CharField(verbose_name='文章标签', max_length=20)
    number = models.IntegerField(verbose_name='标签数目', default=1)
    class Meta:
        verbose_name = '文章标签'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


# 文章
class Article(models.Model):
    author = models.ForeignKey(to=Users, on_delete=models.CASCADE, verbose_name='作者')
    title = models.CharField(max_length=150, verbose_name='文章标题')
    summary = models.TextField(verbose_name='文章摘要', max_length=230, default='文章摘要等同于网页description内容，请务必填写...')
    # 文章内容（普通字段models.TextField(verbose_name='文章内容')）
    body = MDTextField(verbose_name='文章内容')
    # 图片链接
    image = models.ImageField(blank=True, null=True, verbose_name='文章图片', upload_to='uploads/article/%Y/%m/%d')
    # 自动添加创建时间
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    # 自动添加修改时间
    update_date = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    # 浏览点赞整数字段
    views = models.IntegerField(verbose_name='阅览量', default=0)
    loves = models.IntegerField(verbose_name='喜爱量', default=0)
    # 分类一对多文章 #related_name反向查询
    category = models.ForeignKey(to=Category, on_delete=models.CASCADE, verbose_name='文章分类')
    # 标签多对多文章
    tags = models.ManyToManyField(to=Tag, verbose_name='标签')


    class Meta:
        verbose_name = '博文'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return self.title[:20]


    # 将内容markdown
    def body_to_markdown(self):
        return markdown.markdown(self.body, extensions=[
            # 包含 缩写、表格等常用扩展
            'markdown.extensions.extra',
            # 语法高亮扩展
            'markdown.extensions.codehilite',
            # 自动生成目录扩展
            'markdown.extensions.toc',
        ])

    # 点赞+1方法
    def update_loves(self):
        self.loves += 1
        self.save(update_fields=['loves'])  # 更新字段

    # 浏览+1方法
    def update_views(self):
        self.views += 1
        self.save(update_fields=['views'])  # 更新字段

    # 前篇方法：当前小于文章并倒序排列的第一个
    def get_pre(self):
        return Article.objects.filter(id__lt=self.id).order_by('-id').first()

    # 后篇方法：当前大于文章并正序排列的第一个
    def get_next(self):
        return Article.objects.filter(id__gt=self.id).order_by('id').first()

    def image_url(self):
        if self.image and hasattr(self.image, 'url'):
            return self.image.url
        else:
            return '/static/images/article/default.jpg'


class Banner(ModelBase):
    PRI_CHOICES = [
        (1, '第一级'),
        (2, '第二级'),
        (3, '第三级'),
        (4, '第四级'),
        (5, '第五级'),
        (6, '第六级'),
    ]
    image_url = models.ImageField(verbose_name='轮播图', upload_to='uploads/article/%Y/%m/%d')
    priority = models.IntegerField(choices=PRI_CHOICES, default=6, verbose_name='轮播图优先级')
    news = models.OneToOneField('Article', on_delete=models.CASCADE)

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = 'tb_banner'
        verbose_name = '轮播图'

    def __str__(self):
        return '轮播图{}'.format(self.id)


class HotNews(ModelBase):
    PRI_CHOICES = [
        (1, '第一级'),
        (2, '第二级'),
        (3, '第三级'),
    ]
    news = models.OneToOneField('Article', on_delete=models.CASCADE)
    priority = models.IntegerField(choices=PRI_CHOICES, verbose_name='热门新闻优先级')

    class Meta:
        ordering = ['-update_time', '-id']
        db_table = 'tb_hot'
        verbose_name = '热门新闻'

    def __str__(self):
        return '热门新闻{}'.format(self.id)

extra_apps/xadmin/views/base.py
import copy
import functools
import datetime
import decimal
from functools import update_wrapper
from inspect import getfullargspec

from django import forms
from django.apps import apps
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import get_permission_codename
from django.core.exceptions import ValidationError
from django.core.serializers.json import DjangoJSONEncoder
from django.urls.base import reverse
from django.http import HttpResponse
from django.template import Context, Template
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.decorators import method_decorator, classonlymethod
from django.utils.encoding import force_text, smart_text, smart_str
from django.utils.functional import Promise
from django.utils.http import urlencode
from django.utils.itercompat import is_iterable
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _
from django.views.decorators.csrf import csrf_protect
from django.views.generic import View
from collections import OrderedDict
from xadmin.util import static, json, vendor, sortkeypicker

from xadmin.models import Log

csrf_protect_m = method_decorator(csrf_protect)


class IncorrectPluginArg(Exception):
    pass


def get_content_type_for_model(obj):
    from django.contrib.contenttypes.models import ContentType
    return ContentType.objects.get_for_model(obj, for_concrete_model=False)


def filter_chain(filters, token, func, *args, **kwargs):
    if token == -1:
        return func()
    else:
        def _inner_method():
            fm = filters[token]
            fargs = getfullargspec(fm)[0]
            if len(fargs) == 1:
                # Only self arg
                result = func()
                if result is None:
                    return fm()
                else:
                    raise IncorrectPluginArg(u'Plugin filter method need a arg to receive parent method result.')
            else:
                return fm(func if fargs[1] == '__' else func(), *args, **kwargs)
        return filter_chain(filters, token - 1, _inner_method, *args, **kwargs)


def filter_hook(func):
    tag = func.__name__
    func.__doc__ = "``filter_hook``\n\n" + (func.__doc__ or "")

    @functools.wraps(func)
    def method(self, *args, **kwargs):

        def _inner_method():
            return func(self, *args, **kwargs)

        if self.plugins:
            filters = [(getattr(getattr(p, tag), 'priority', 10), getattr(p, tag))
                       for p in self.plugins if callable(getattr(p, tag, None))]
            filters = [f for p, f in sorted(filters, key=lambda x:x[0])]
            return filter_chain(filters, len(filters) - 1, _inner_method, *args, **kwargs)
        else:
            return _inner_method()
    return method


def inclusion_tag(file_name, context_class=Context, takes_context=False):
    def wrap(func):
        @functools.wraps(func)
        def method(self, context, nodes, *arg, **kwargs):
            _dict = func(self, context, nodes, *arg, **kwargs)
            from django.template.loader import get_template, select_template
            cls_str = str if six.PY3 else basestring
            if isinstance(file_name, Template):
                t = file_name
            elif not isinstance(file_name, cls_str) and is_iterable(file_name):
                t = select_template(file_name)
            else:
                t = get_template(file_name)

            _dict['autoescape'] = context.autoescape
            _dict['use_l10n'] = context.use_l10n
            _dict['use_tz'] = context.use_tz
            _dict['admin_view'] = context['admin_view']

            csrf_token = context.get('csrf_token', None)
            if csrf_token is not None:
                _dict['csrf_token'] = csrf_token
            nodes.append(t.render(_dict))

        return method
    return wrap


class JSONEncoder(DjangoJSONEncoder):

    def default(self, o):
        if isinstance(o, datetime.datetime):
            return o.strftime('%Y-%m-%d %H:%M:%S')
        elif isinstance(o, datetime.date):
            return o.strftime('%Y-%m-%d')
        elif isinstance(o, decimal.Decimal):
            return str(o)
        elif isinstance(o, Promise):
            return force_text(o)
        else:
            try:
                return super(JSONEncoder, self).default(o)
            except Exception:
                return smart_text(o)


class BaseAdminObject(object):

    def get_view(self, view_class, option_class=None, *args, **kwargs):
        opts = kwargs.pop('opts', {})
        return self.admin_site.get_view_class(view_class, option_class, **opts)(self.request, *args, **kwargs)

    def get_model_view(self, view_class, model, *args, **kwargs):
        return self.get_view(view_class, self.admin_site._registry.get(model), *args, **kwargs)

    def get_admin_url(self, name, *args, **kwargs):
        return reverse('%s:%s' % (self.admin_site.app_name, name), args=args, kwargs=kwargs)

    def get_model_url(self, model, name, *args, **kwargs):
        return reverse(
            '%s:%s_%s_%s' % (self.admin_site.app_name, model._meta.app_label,
                             model._meta.model_name, name),
            args=args, kwargs=kwargs, current_app=self.admin_site.name)

    def get_model_perm(self, model, name):
        return '%s.%s_%s' % (model._meta.app_label, name, model._meta.model_name)

    def has_model_perm(self, model, name, user=None):
        user = user or self.user
        return user.has_perm(self.get_model_perm(model, name)) or (name == 'view' and self.has_model_perm(model, 'change', user))

    def get_query_string(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return '?%s' % urlencode(p)

    def get_form_params(self, new_params=None, remove=None):
        if new_params is None:
            new_params = {}
        if remove is None:
            remove = []
        p = dict(self.request.GET.items()).copy()
        arr_keys = list(p.keys())
        for r in remove:
            for k in arr_keys:
                if k.startswith(r):
                    del p[k]
        for k, v in new_params.items():
            if v is None:
                if k in p:
                    del p[k]
            else:
                p[k] = v
        return mark_safe(''.join(
            '<input type="hidden" name="%s" value="%s"/>' % (k, v) for k, v in p.items() if v))

    def render_response(self, content, response_type='json'):
        if response_type == 'json':
            response = HttpResponse(content_type="application/json; charset=UTF-8")
            response.write(
                json.dumps(content, cls=JSONEncoder, ensure_ascii=False))
            return response
        return HttpResponse(content)

    def template_response(self, template, context):
        return TemplateResponse(self.request, template, context)

    def message_user(self, message, level='info'):
        """
        Send a message to the user. The default implementation
        posts a message using the django.contrib.messages backend.
        """
        if hasattr(messages, level) and callable(getattr(messages, level)):
            getattr(messages, level)(self.request, message)

    def static(self, path):
        return static(path)

    def vendor(self, *tags):
        return vendor(*tags)

    def log(self, flag, message, obj=None):
        log = Log(
            user=self.user,
            ip_addr=self.request.META['REMOTE_ADDR'],
            action_flag=flag,
            message=message
        )
        if obj:
            log.content_type = get_content_type_for_model(obj)
            log.object_id = obj.pk
            log.object_repr = force_text(obj)
        log.save()


class BaseAdminPlugin(BaseAdminObject):

    def __init__(self, admin_view):
        self.admin_view = admin_view
        self.admin_site = admin_view.admin_site

        if hasattr(admin_view, 'model'):
            self.model = admin_view.model
            self.opts = admin_view.model._meta

    def init_request(self, *args, **kwargs):
        pass


class BaseAdminView(BaseAdminObject, View):
    """ Base Admin view, support some comm attrs."""

    base_template = 'xadmin/base.html'
    need_site_permission = True

    def __init__(self, request, *args, **kwargs):
        self.request = request
        self.request_method = request.method.lower()
        self.user = request.user

        self.base_plugins = [p(self) for p in getattr(self,
                                                      "plugin_classes", [])]

        self.args = args
        self.kwargs = kwargs
        self.init_plugin(*args, **kwargs)
        self.init_request(*args, **kwargs)

    @classonlymethod
    def as_view(cls):
        def view(request, *args, **kwargs):
            self = cls(request, *args, **kwargs)

            if hasattr(self, 'get') and not hasattr(self, 'head'):
                self.head = self.get

            if self.request_method in self.http_method_names:
                handler = getattr(
                    self, self.request_method, self.http_method_not_allowed)
            else:
                handler = self.http_method_not_allowed

            return handler(request, *args, **kwargs)

        # take name and docstring from class
        update_wrapper(view, cls, updated=())
        view.need_site_permission = cls.need_site_permission

        return view

templates/base/base.html
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <meta name="keywords" content="个人博客,路远个人博客,个人博客模板,路远"/>
  <meta name="description" content="路远个人博客，是一个专注于后端开发的程序员的个人网站，不定时分享各种学习资源，技术文章和生活感悟。"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% block link %}
  {% endblock %}
  <link href="{% static 'css/base.css' %}" rel="stylesheet">
  <link href="{% static 'css/index.css' %}" rel="stylesheet">
  <link href="{% static 'css/m.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/jquery.easyfader.min.js' %}"></script>
  <script src="{% static 'js/scrollReveal.js' %}"></script>
  <script src="{% static 'js/common.js' %}"></script>

  <!--[if lt IE 9]>
<script src="js/modernizr.js"></script>
<![endif]-->
</head>
<body>
<header>
  <!--menu begin-->
  <div class="menu">
    <nav class="nav" id="topnav">
      <h1 class="logo"><a href="http://www.bloglu.cn">路远的博客</a></h1>
      <li><a href="/">网站首页</a></li>
      <li><a href="#">关于我</a></li>
      {% for big_c in nodes %}
        <li><a href="{% url 'article:study' big_c.name %}">{{ big_c.name }}</a>
          <ul class="sub-nav">
            {% for category in big_c.category_set.all %}
              <li><a href="{% url 'article:study' category.name %}">{{ category.name }}</a></li>
            {% endfor %}
          </ul>
        </li>
      {% endfor %}
      <li><a href="#">时间轴</a></li>
      <li><a href="{% url 'life:message' %}">留言</a></li>
      {#      <li><a href="{% url 'article:info' %}">内容页</a></li>#}
      <!--search begin-->
      <div id="search_bar" class="search_bar">
        <form id="searchform" action="[!--news.url--]e/search/index.php" method="post" name="searchform">
          <input class="input" placeholder="想搜点什么呢..." type="text" name="keyboard" id="keyboard">
          <input type="hidden" name="show" value="title"/>
          <input type="hidden" name="tempid" value="1"/>
          <input type="hidden" name="tbname" value="news">
          <input type="hidden" name="Submit" value="搜索"/>
          <span class="search_ico"></span>
        </form>
      </div>
      <!--search end-->
    </nav>
  </div>
  <!--menu end-->
</header>

{% block image %}
{% endblock %}
{% block main %}
  <div class="container">
    {% block h1_blogbox %}
    {% endblock %}
    <div class="sidebar">
      <div class="zhuanti">
        <h2 class="hometitle">特别推荐</h2>
        <ul>
          {% for ban in banners|slice:'3:' %}
            <li>
              <i><img src="{{ ban.news.image_url }}"></i>
              <p>{{ ban.news.title }}
                <span>
                  <a href="{% url 'article:info' %}?id={{ ban.news.id }}">阅读</a>
                </span>
              </p>
            </li>
          {% endfor %}
        </ul>
      </div>
      {#      <div class="tuijian">#}
      {#        <h2 class="hometitle">推荐文章</h2>#}
      {#        <ul class="tjpic">#}
      {#          <i><img src="../../static/images/toppic01.jpg"></i>#}
      {#          <p><a href="/">别让这些闹心的套路，毁了你的网页设计</a></p>#}
      {#        </ul>#}
      {#        <ul class="sidenews">#}
      {#          <li><i><img src="../../static/images/toppic01.jpg"></i>#}
      {#            <p><a href="/">别让这些闹心的套路，毁了你的网页设计</a></p>#}
      {#            <span>2018-05-13</span></li>#}
      {#          <li><i><img src="../../static/images/toppic02.jpg"></i>#}
      {#            <p><a href="/">给我模板PSD源文件，我给你设计HTML！</a></p>#}
      {#            <span>2018-05-13</span></li>#}
      {#          <li><i><img src="../../static/images/v1.jpg"></i>#}
      {#            <p><a href="/">别让这些闹心的套路，毁了你的网页设计</a></p>#}
      {#            <span>2018-05-13</span></li>#}
      {#          <li><i><img src="../../static/images/v2.jpg"></i>#}
      {#            <p><a href="/">给我模板PSD源文件，我给你设计HTML！</a></p>#}
      {#            <span>2018-05-13</span></li>#}
      {#        </ul>#}
      {#      </div>#}
      <div class="tuijian">
        <h2 class="hometitle">点击排行</h2>
        <ul class="tjpic">
          <i><img src="{{ view_articles.first.image_url }}"></i>
          <p><a href="{% url 'article:info' %}?id={{ view_articles.first.id }}">{{ view_articles.first.title }}</a></p>
        </ul>
        <ul class="sidenews">
          {% for view_article in view_articles|slice:'1:' %}
            <li><i><img src="{{ view_article.image_url }}"></i>
              <p><a href="{% url 'article:info' %}?id={{ view_article.id }}">{{ view_article.title }}</a></p>
              <span>{{ view_article.create_date|date:'Y-m-d' }}</span></li>
          {% endfor %}
        </ul>
      </div>
      <div class="cloud">
        <h2 class="hometitle">标签云</h2>
        <ul>
          {% for tag in tags %}
            <a href="/">{{ tag.name }}</a>
          {% endfor %}
        </ul>
      </div>

      <div class="guanzhu" id="follow-us">
        <h2 class="hometitle">关注我们 么么哒！</h2>
        <ul>
           <li class="sina"><a href="/" target="_blank"><span>新浪微博</span>路远博客</a></li>
          <li class="tencent"><a href="/" target="_blank"><span>简书账号</span>路远博客</a></li>
          <li class="qq"><a href="/" target="_blank"><span>QQ号</span>643739651</a></li>
          <li class="email"><a href="/" target="_blank"><span>邮箱帐号</span>643739651@qq.com</a></li>
          <li class="wxgzh"><a href="/" target="_blank"><span>微信号</span>15971466561</a></li>
          <li class="wx"><img src="{% static 'images/wzp.jpg' %}"></li>
        </ul>
      </div>
    </div>
  </div>
{% endblock %}

<footer>
  <p>Design by <a href="http://www.yangqq.com" target="_blank">路远个人博客</a> <a href="/">蜀ICP备11002373号-1</a></p>
</footer>
{% block top %}
  <a href="#" class="cd-top">Top</a>
{% endblock %}
{% block script %}
{% endblock %}
</body>
</html>