apps/article/urls.py
from django.urls import path
from . import views


app_name = 'article'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('info/', views.InfoView.as_view(), name='info'),
    path('study/<name>', views.StudyView.as_view(), name='study'),
]


apps/life/urls.py
from django.urls import path
from . import views


app_name = 'life'
urlpatterns = [
    path('time/', views.time, name='time'),
    path('about/', views.about, name='about'),
    path('message/', views.Message.as_view(), name='message'),
]


apps/users/urls.py
from django.urls import path
from . import views


app_name = 'users'
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name='register'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
]

lublog/urls.py
import xadmin
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    # path('admin/', admin.site.urls),
    path('admin/', xadmin.site.urls),  # 后台管理界面插件
    path('mdeditor/', include('mdeditor.urls')),  # markdown插件
    path('users/', include('users.urls')),
    path('', include('article.urls')),
    path('', include('verifications.urls')),
    path('lifes/', include('life.urls'))
]

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/life/models.py
# life/models.py
from django.db import models

from article.models import Article


class Message(models.Model):
    username = models.CharField(max_length=50, verbose_name='昵称')
    content = models.TextField(verbose_name='内容', default='请留下联系方式')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='时间')

    class Meta:
        verbose_name = '留言'
        verbose_name_plural = verbose_name
        ordering = ['-create_date']

    def __str__(self):
        return self.username


class Comment(models.Model):
    """文章评论"""
    nickname = models.CharField(max_length=50, verbose_name='昵称')
    content = models.TextField(verbose_name='内容')
    create_date = models.DateTimeField(auto_now=True, verbose_name='评论时间')
    article = models.ForeignKey(to=Article, on_delete=models.CASCADE, verbose_name='对应的文章')

    class Meta:
        verbose_name = '文章评论'
        verbose_name_plural=verbose_name

    def __str__(self):
        return self.nickname

apps/life/forms.py
from django import forms
from .models import Message,Comment

BIRTH_YEAR_CHOICES = ('1980', '1981', '1982')
FAVORITE_COLORS_CHOICES = (
    ('blue', 'Blue'),
    ('green', 'Green'),
    ('black', 'Black'),
)


class BlogForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

apps/life/views.py
from django.shortcuts import render
from django.views import View
from django.http import JsonResponse

from life.forms import BlogForm
from .models import Message as Mes, Comment


def about(request):
    return render(request, 'aboutme.html')

def time(request):
    return render(request, 'time.html')


class Message(View):
    def get(self,request):
        # 评论表单
        blog_form = BlogForm()
        message = Mes.objects.all()
        return render(request, 'message.html', {'blog_form': blog_form, 'message':message})

    def post(self, request):
        blog_form = BlogForm(request.POST)
        if blog_form.is_valid():
            username = request.POST.get('username')
            content = request.POST.get('content')

            Mes.objects.create(username=username, content=content)
            message = Mes.objects.all()
            blog_form = BlogForm()
            return render(request, 'message.html', {'blog_form': blog_form, 'message':message})

extra_apps/xadmin/views/list.py
from __future__ import absolute_import
from collections import OrderedDict
from django.core.exceptions import PermissionDenied, ObjectDoesNotExist
from django.core.paginator import InvalidPage, Paginator
from django.urls.base import NoReverseMatch
from django.db import models
from django.http import HttpResponseRedirect
from django.template.response import SimpleTemplateResponse, TemplateResponse
from django.utils import six
from django.utils.encoding import force_text, smart_text
from django.utils.html import escape, conditional_escape
from django.utils.safestring import mark_safe
from django.utils.text import capfirst
from django.utils.translation import ugettext as _

from xadmin.util import lookup_field, display_for_field, label_for_field, boolean_icon

from .base import ModelAdminView, filter_hook, inclusion_tag, csrf_protect_m

# List settings
ALL_VAR = 'all'
ORDER_VAR = 'o'
PAGE_VAR = 'p'
TO_FIELD_VAR = 't'
COL_LIST_VAR = '_cols'
ERROR_FLAG = 'e'

DOT = '.'

# Text to display within change-list table cells if the value is blank.
EMPTY_CHANGELIST_VALUE = _('Null')


class FakeMethodField(object):
    """
    This class used when a column is an model function, wrap function as a fake field to display in select columns.
    """

    def __init__(self, name, verbose_name):
        # Initial comm field attrs
        self.name = name
        self.verbose_name = verbose_name
        self.primary_key = False


class ResultRow(dict):
    pass


class ResultItem(object):

    def __init__(self, field_name, row):
        self.classes = []
        self.text = '&nbsp;'
        self.wraps = []
        self.tag = 'td'
        self.tag_attrs = []
        self.allow_tags = False
        self.btns = []
        self.menus = []
        self.is_display_link = False
        self.row = row
        self.field_name = field_name
        self.field = None
        self.attr = None
        self.value = None

    @property
    def label(self):
        text = mark_safe(
            self.text) if self.allow_tags else conditional_escape(self.text)
        if force_text(text) == '':
            text = mark_safe('&nbsp;')
        for wrap in self.wraps:
            text = mark_safe(wrap % text)
        return text

    @property
    def tagattrs(self):
        return mark_safe(
            '%s%s' % ((self.tag_attrs and ' '.join(self.tag_attrs) or ''),
                      (self.classes and (' class="%s"' % ' '.join(self.classes)) or '')))


class ResultHeader(ResultItem):

    def __init__(self, field_name, row):
        super(ResultHeader, self).__init__(field_name, row)
        self.tag = 'th'
        self.tag_attrs = ['scope="col"']
        self.sortable = False
        self.allow_tags = True
        self.sorted = False
        self.ascending = None
        self.sort_priority = None
        self.url_primary = None
        self.url_remove = None
        self.url_toggle = None


class ListAdminView(ModelAdminView):
    """
    Display models objects view. this class has ordering and simple filter features.
    """
    list_display = ('__str__',)
    list_display_links = ()
    list_display_links_details = False
    list_select_related = None
    list_per_page = 50
    list_max_show_all = 200
    list_exclude = ()
    search_fields = ()
    paginator_class = Paginator
    ordering = None

    # Change list templates
    object_list_template = None

    def init_request(self, *args, **kwargs):

        if not self.has_view_permission():
            raise PermissionDenied

        request = self.request
        request.session['LIST_QUERY'] = (self.model_info, self.request.META['QUERY_STRING'])

        self.pk_attname = self.opts.pk.attname
        self.lookup_opts = self.opts
        self.list_display = self.get_list_display()
        self.list_display_links = self.get_list_display_links()

        # Get page number parameters from the query string.
        try:
            self.page_num = int(request.GET.get(PAGE_VAR, 0))
        except ValueError:
            self.page_num = 0

        # Get params from request
        self.show_all = ALL_VAR in request.GET
        self.to_field = request.GET.get(TO_FIELD_VAR)
        self.params = dict(request.GET.items())

        if PAGE_VAR in self.params:
            del self.params[PAGE_VAR]
        if ERROR_FLAG in self.params:
            del self.params[ERROR_FLAG]

    @filter_hook
    def get_list_display(self):
        """
        Return a sequence containing the fields to be displayed on the list.
        """
        self.base_list_display = (COL_LIST_VAR in self.request.GET and self.request.GET[COL_LIST_VAR] != "" and
                                  self.request.GET[COL_LIST_VAR].split('.')) or self.list_display
        return list(self.base_list_display)

    @filter_hook
    def get_list_display_links(self):
        """
        Return a sequence containing the fields to be displayed as links
        on the changelist. The list_display parameter is the list of fields
        returned by get_list_display().
        """
        if self.list_display_links or not self.list_display:
            return self.list_display_links
        else:
            # Use only the first item in list_display as link
            return list(self.list_display)[:1]

    def make_result_list(self):
        # Get search parameters from the query string.
        self.list_queryset = self.get_list_queryset()
        self.ordering_field_columns = self.get_ordering_field_columns()
        self.paginator = self.get_paginator()

        # Get the number of objects, with admin filters applied.
        self.result_count = self.paginator.count

        self.can_show_all = self.result_count <= self.list_max_show_all
        self.multi_page = self.result_count > self.list_per_page

        # Get the list of objects to display on this page.
        if (self.show_all and self.can_show_all) or not self.multi_page:
            self.result_list = self.list_queryset._clone()
        else:
            try:
                self.result_list = self.paginator.page(
                    self.page_num + 1).object_list
            except InvalidPage:
                if ERROR_FLAG in self.request.GET.keys():
                    return SimpleTemplateResponse('xadmin/views/invalid_setup.html', {
                        'title': _('Database error'),
                    })
                return HttpResponseRedirect(self.request.path + '?' + ERROR_FLAG + '=1')
        self.has_more = self.result_count > (
            self.list_per_page * self.page_num + len(self.result_list))

    @filter_hook
    def get_result_list(self):
        return self.make_result_list()

    @filter_hook
    def post_result_list(self):
        return self.make_result_list()

    @filter_hook
    def get_list_queryset(self):
        """
        Get model queryset. The query has been filted and ordered.
        """
        # First, get queryset from base class.
        queryset = self.queryset()

        # Use select_related() if one of the list_display options is a field
        # with a relationship and the provided queryset doesn't already have
        # select_related defined.
        if not queryset.query.select_related:
            if self.list_select_related:
                queryset = queryset.select_related()
            elif self.list_select_related is None:
                related_fields = []
                for field_name in self.list_display:
                    try:
                        field = self.opts.get_field(field_name)
                    except models.FieldDoesNotExist:
                        pass
                    else:
                        if isinstance(field.remote_field, models.ManyToOneRel):
                            related_fields.append(field_name)
                if related_fields:
                    queryset = queryset.select_related(*related_fields)
            else:
                pass

        # Then, set queryset ordering.
        queryset = queryset.order_by(*self.get_ordering())

        # Return the queryset.
        return queryset

    # List ordering
    def _get_default_ordering(self):
        ordering = []
        if self.ordering:
            ordering = self.ordering
        elif self.opts.ordering:
            ordering = self.opts.ordering
        return ordering

    @filter_hook
    def get_ordering_field(self, field_name):
        """
        Returns the proper model field name corresponding to the given
        field_name to use for ordering. field_name may either be the name of a
        proper model field or the name of a method (on the admin or model) or a
        callable with the 'admin_order_field' attribute. Returns None if no
        proper model field name can be matched.
        """
        try:
            field = self.opts.get_field(field_name)
            return field.name
        except models.FieldDoesNotExist:
            # See whether field_name is a name of a non-field
            # that allows sorting.
            if callable(field_name):
                attr = field_name
            elif hasattr(self, field_name):
                attr = getattr(self, field_name)
            else:
                attr = getattr(self.model, field_name)
            return getattr(attr, 'admin_order_field', None)

    @filter_hook
    def get_ordering(self):
        """
        Returns the list of ordering fields for the change list.
        First we check the get_ordering() method in model admin, then we check
        the object's default ordering. Then, any manually-specified ordering
        from the query string overrides anything. Finally, a deterministic
        order is guaranteed by ensuring the primary key is used as the last
        ordering field.
        """
        ordering = list(super(ListAdminView, self).get_ordering()
                        or self._get_default_ordering())
        if ORDER_VAR in self.params and self.params[ORDER_VAR]:
            # Clear ordering and used params

templates/info.html
{% extends 'life.html' %}
{% block title %}
  内容详情
{% endblock %}
{% block link %}
  <link rel="stylesheet" href="{% static 'css/ssssss.css' %}">
{% endblock %}

{% block h1_blogbox %}
  <h1 class="t_nav"><span>您现在的位置是：
    <a href="/">首页</a> >
    <a href="{% url 'article:study' article.category.bigcategory %}">{{ article.category.bigcategory }}</a> >
    <a href="{% url 'article:study' article.category %}">{{ article.category }}</a></span>
    <a href="/" class="n1">网站首页</a>
    <a href="{% url 'article:study' article.category %}" class="n2">{{ article.category }}</a>
  </h1>
  <div class="infosbox">
    <div class="newsview">
      <h3 class="news_title">{{ article.title }}</h3>
      <div class="bloginfo">
        <ul>
          <li class="author"><a href="/">{{ article.author }}</a></li>
          <li class="lmname"><a href="#">{{ article.category }}</a></li>
          <li class="timer">{{ article.create_date | date:'Y-m-d' }}</li>
          <li class="view">{{ article.views }}已阅读</li>
          <li class="like">{{ article.loves }}</li>
        </ul>
      </div>
      <div class="tags"><a href="/" target="_blank">个人博客</a> &nbsp; <a href="/" target="_blank">小世界</a></div>
      <div class="news_about"><strong>简介</strong>{{ article.summary }}
      </div>
      {#        <div class="news_con">#}
      <div class="markdown">
        {{ article.body_to_markdown | safe }}
        <br>
        &nbsp;
      </div>
    </div>
    <div class="share">
      <p class="diggit">
        {#          <a href="JavaScript:makeRequest('/e/public/digg/?classid=3&amp;id=19&amp;dotop=1&amp;doajax=1&amp;ajaxarea=diggnum','EchoReturnedText','GET','');">#}
        <a href="{% url 'article:info' %}" id="">
          很赞哦！
        </a>(<b id="diggnum">{{ article.loves }}</b>)
      </p>
      <p class="dasbox"><a href="javascript:void(0)" onClick="dashangToggle()" class="dashang"
                           title="打赏，支持一下">打赏本站</a></p>
      <div class="hide_box"></div>
      <div class="shang_box"><a class="shang_close" href="javascript:void(0)" onclick="dashangToggle()"
                                title="关闭">关闭</a>
        <div class="shang_tit">
          <p>感谢您的支持，我会继续努力的!</p>
        </div>
        <div class="shang_payimg"><img src="../static/images/alipayimg.jpg" alt="扫码支持" title="扫一扫"></div>
        <div class="pay_explain">扫码打赏，你说多少就多少</div>
        <div class="shang_payselect">
          <div class="pay_item checked" data-id="alipay"><span class="radiobox"></span> <span class="pay_logo"><img
                  src="../static/images/alipay.jpg" alt="支付宝"></span></div>
          <div class="pay_item" data-id="weipay"><span class="radiobox"></span> <span class="pay_logo"><img
                  src="../static/images/wechat.jpg" alt="微信"></span></div>
        </div>
        <script type="text/javascript">
          $(function () {
            $(".pay_item").click(function () {
              $(this).addClass('checked').siblings('.pay_item').removeClass('checked');
              var dataid = $(this).attr('data-id');
              $(".shang_payimg img").attr("src", "images/" + dataid + "img.jpg");
              $("#shang_pay_txt").text(dataid == "alipay" ? "支付宝" : "微信");
            });
          });

          function dashangToggle() {
            $(".hide_box").fadeToggle();
            $(".shang_box").fadeToggle();
          }
        </script>
      </div>
    </div>
    <div class="nextinfo">
      <p>上一篇：<a href="{% url 'article:info' %}?id={{ article.get_pre.id }}">{{ article.get_pre.title }}</a></p>
      <p>下一篇：<a href="{% url 'article:info' %}?id={{ article.get_next.id }}">{{ article.get_next.title }}</a></p>
    </div>
    <div class="otherlink">
      <h2>相关文章</h2>
      <ul>
        <li><a href="/download/div/2018-04-22/815.html" title="html5个人博客模板《黑色格调》">html5个人博客模板《黑色格调》</a></li>
        <li><a href="/download/div/2018-04-18/814.html" title="html5个人博客模板主题《清雅》">html5个人博客模板主题《清雅》</a></li>
        <li><a href="/download/div/2018-03-18/807.html" title="html5个人博客模板主题《绅士》">html5个人博客模板主题《绅士》</a></li>
        <li><a href="/download/div/2018-02-22/798.html" title="html5时尚个人博客模板-技术门户型">html5时尚个人博客模板-技术门户型</a></li>
        <li><a href="/download/div/2017-09-08/789.html" title="html5个人博客模板主题《心蓝时间轴》">html5个人博客模板主题《心蓝时间轴》</a></li>
        <li><a href="/download/div/2017-07-16/785.html" title="古典个人博客模板《江南墨卷》">古典个人博客模板《江南墨卷》</a></li>
        <li><a href="/download/div/2017-07-13/783.html" title="古典风格-个人博客模板">古典风格-个人博客模板</a></li>
        <li><a href="/download/div/2015-06-28/748.html" title="个人博客《草根寻梦》—手机版模板">个人博客《草根寻梦》—手机版模板</a></li>
        <li><a href="/download/div/2015-04-10/746.html" title="【活动作品】柠檬绿兔小白个人博客模板">【活动作品】柠檬绿兔小白个人博客模板</a></li>
        <li><a href="/jstt/bj/2015-01-09/740.html" title="【匆匆那些年】总结个人博客经历的这四年…">【匆匆那些年】总结个人博客经历的这四年…</a></li>
      </ul>
    </div>
    <div class="news_pl">
      <h2>文章评论</h2>
      <ul>
        <div class="gbko">
          <div class="gbox">
            <form action="{% url 'article:info' %}?id={{ article.id }}" method="post">{% csrf_token %}
              这是表单
              <p><span>来说句话吧...</span><span>评论总数：</span></p>
              <p><input type="text" name="nickname" placeholder="请输入昵称"></p>
              <p><textarea name="content" cols="80" rows="10"></textarea></p>
              <p><input type="submit" value="评论" id="btncomment"></p>
            </form>
          </div>
          <br>
          <h2 class="htitle">留言板<p style="float: right">留言总数：{{ comments.count }}条</p></h2>

          <div style="border: #000 2px solid; padding: 10px">
            <div>
              {% for mes in comments %}
                <div class="fb" style="padding-top: 10px; border-bottom: 1px solid darkgray">
                  <p style="font-weight: bold; float: left">{{ mes.nickname }}</p>
                  <p style="float: right">{{ mes.create_date }}</p>
                  <br>
                  <span>{{ mes.content }}</span>
                </div>
              {% endfor %}
            </div>
            <div>
              <div class="fb" style="padding-top: 10px; border-bottom: 1px solid darkgray">
                <p style="font-weight: bold; float: left">username</p>
                <p style="float: right">time</p>
                <br>
                <span>content</span>
              </div>
            </div>
            <!--newsinfo end-->
          </div>
        </div>
      </ul>
    </div>
  </div>
{% endblock %}

templates/life.html
{% extends 'base/base.html' %}
{% block title %}
  {{ bigCategory.name }}
{% endblock %}

{% block image %}
  <div class="pagebg sh"></div>
{% endblock %}

{% block h1_blogbox %}
  <h1 class="t_nav">
      <span>
        {{ big_desc }}
      </span>
    <a href="{% url 'article:index' %}" class="n1">网站首页</a>
    <a href="{% url 'article:study' name %}" class="n2">{{ name }}</a>
  </h1>

  <!--blogsbox begin-->
  <div class="blogsbox">
    {% for article in contacts.object_list %}
      <div class="blogs" data-scroll-reveal="enter bottom over 1s">
        <h3 class="blogtitle">
          <a href="{% url 'article:info' %}?id={{ article.id }}" target="_blank">
            {{ article.title }}
          </a>
        </h3>
        <span class="blogpic">
            <a href="{% url 'article:info' %}?id={{ article.id }}" title="">
              <img src="{{ article.image_url }}" alt="">
            </a>
          </span>
        <p class="blogtext">{{ article.summary }}</p>
        <div class="bloginfo">
          <ul>
            <li class="author"><a href="#">{{ article.author }}</a></li>
            <li class="lmname"><a href="#">{{ article.category }}</a></li>
            <li class="timer">{{ article.create_date | date:'Y-m-d' }}</li>
            <li class="view"><span>{{ article.views }}</span>已阅读</li>
            <li class="like">{{ article.loves }}</li>
          </ul>
        </div>
      </div>
    {% endfor %}

    <div class="pagelist">
      <a title="Total record">
        <b>&nbsp;{{ contacts.paginator.num_pages }}</b>
      </a>&nbsp;&nbsp;&nbsp;

      {% if contacts.has_previous %}
        <a href="?page=1">首页</a>
        <a href="?page={{ contacts.previous_page_number }}">上一页</a>&nbsp;
      {% endif %}

      {% for page_num in page_contacts.object_list %}
        {#            <p>{{ page_num }}</p>#}
        {% if page_num == contacts.number %}
          <b>{{ contacts.number }}</b>&nbsp;
        {% else %}
          <a href="?page={{ page_num }}">{{ page_num }}</a>
        {% endif %}
      {% endfor %}

      {% if contacts.has_next %}
        <a href="?page={{ contacts.next_page_number }}">下一页</a>&nbsp;
        <a href="?page={{ contacts.paginator.num_pages }}">尾页</a>
      {% endif %}
    </div>
  </div>
  <!--blogsbox end-->
{% endblock %}


templates/login.html
{% extends 'base/../static/base.html' %}
{% block title %}
  注册
{% endblock %}
{% block link %}
  <link rel="stylesheet" href="{% static 'css/auth.css' %}">
{% endblock %}

<!-- container start -->
{% block article %}
  <article>
    <div id="blogsbox">
      <div id="container">
        <div class="login-contain">
          <div class="top-contain">
            <a href="{% url 'users:login' %}" class="please-login">用户名登录</a>/
            <a href="{% url 'users:codelogin' %}" class="please-login">手机号登录</a>
            {#      <a href="javascript:void(0);" class="register">立即注册 &gt;</a>#}
            <a href="{% url 'users:register' %}" class="register">立即注册 &gt;</a>
          </div>
          <form action="{% url 'users:login' %}" method="post" class="form-contain">
            {% csrf_token %}
            <div class="form-item">
              <p style="color: red">{{ errors }}</p>
              <input type="text" placeholder="请输入用户名或手机号" name="username" class="form-control" autocomplete="off">
            </div>
            <div class="form-item">
              <input type="password" placeholder="请输入密码" name="password" class="form-control">
            </div>
            <div class="form-item clearfix">
              <label>
                <input type="checkbox" name="remember">
                <span>记住我</span>
              </label>
              <a href="javascript:void(0);" class="forget-password">忘记密码?</a>
            </div>
            <div class="form-login">
              <input type="submit" value="登录" class="login-btn">
            </div>
          </form>
        </div>
      </div>
    </div>
  </article>
{% endblock %}
<!-- container end -->
{% block top %}
{% endblock %}
{% block script %}
  {#  <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>#}
  {#  <script src="{% static 'js/base/common.js' %}"></script>#}
  {#  <script src="{% static 'js/base/message.js' %}"></script>#}
  {#  <script src="{% static 'js/users/auth.js' %}"></script>#}
{% endblock %}

templates/message.html
{% extends 'base/base.html' %}
{% block title %}
  留言区
{% endblock %}

{% block link %}
  <style>
    form p {
      margin: 10px;
    }
  </style>
{% endblock %}

{% block image %}
  <div class="pagebg ab"></div>
{% endblock %}
{% block main %}
  <div class="container">
    <h1 class="t_nav">
      <span>你，我生命中一个重要的过客，我们之所以是过客，因为你未曾会为我停留。</span>
      <a href="/" class="n1">网站首页</a><a href="{% url 'life:message' %}" class="n2">留言</a>
    </h1>

    {% block news_infos %}
      <div class="news_infos">
        <ul>
          <div class="whitebg">
            <h2 class="htitle">写留言</h2>

            <div class="gbox">
              <form action="{% url 'life:message' %}" method="post">{% csrf_token %}
                {{ blog_form.as_p }}
                <input type="submit" value="提交" class="login-btn" style="height: 30px; width: 60px;">

              </form>
            </div>
            <br>
            <h2 class="htitle">留言板<p style="float: right">留言总数：{{ message.count }}条</p></h2>

            <div style="border: #000 2px solid; padding: 10px">
              <div>
                {% for mes in message %}
                  <div class="fb" style="padding-top: 10px; border-bottom: 1px solid darkgray">
                    <p style="font-weight: bold; float: left">{{ mes.username }}</p>
                    <p style="float: right">{{ mes.create_date }}</p>
                    <br>
                    <span>{{ mes.content }}</span>
                  </div>
                {% endfor %}
              </div>
              <div>
                {#              {% for mes in message %}#}
                <div class="fb" style="padding-top: 10px; border-bottom: 1px solid darkgray">

                  <p style="font-weight: bold; float: left">username</p>
                  <p style="float: right">time</p>
                  <br>
                  <span>content</span>

                </div>
                {#              {% endfor %}#}
              </div>
              <!--newsinfo end-->
            </div>
          </div>
        </ul>
      </div>
    {% endblock %}

    <div class="sidebar">
      <div class="about">
        <p class="avatar"><img src="{% static 'images/v1.jpg' %}" alt=""></p>
        <p class="abname">dancesmile | 路远</p>
        <p class="abposition">后端开发工程师</p>
        <p class="abtext"> 一个90后草根站长！一直潜心研究web后端技术，一边工作一边积累经验，分享一些学习资源，生活趣闻，工作经历。 </p>
      </div>
      <div class="weixin">
        <h2 class="hometitle">微信关注</h2>
        <ul>

                    <img src="{% static 'images/wzp.jpg' %}" >
{#          <img src="../static/images/wzp.jpg" style="max-width: 300px">#}
        </ul>
      </div>
    </div>
  </div>
{% endblock %}


templates/register.html
{% extends 'base/../static/base.html' %}
{% block title %}
  注册
{% endblock %}
{% block link %}
  <link rel="stylesheet" href="{% static 'css/auth.css' %}">
{% endblock %}

<!-- container start -->
{% block article %}
  <article>
    <div id="blogsbox">
      <div id="container">
        <div class="register-contain">
          <div class="top-contain">
            <h4 class="please-register">请注册</h4>
            {#      <a href="javascript:void(0);" class="login">立即登录 &gt;</a>#}
            <a href="{% url 'users:login' %}" class="login">立即登录 &gt;</a>
          </div>
          <form action="{% url 'users:register' %}" method="post" class="form-contain">
            {% csrf_token %}
            <div class="form-item">
              <p style="color: red">{{ error_msg }}</p>
              <input type="text" placeholder="请输入用户名" id="username" name="username"
                     class="form-control" required>
            </div>
            <div class="form-item">
              <input type="password" placeholder="请输入密码" id="password" name="password"
                     class="form-control" required>
            </div>
            <div class="form-item">
              <input type="password" placeholder="请输入确认密码" id="password_repeat" name="password_repeat"
                     class="form-control" required>
            </div>
            <div class="form-item">
              <input type="tel" placeholder="请输入手机号" id="mobile" name="mobile"
                     class="form-control" required>
            </div>
            <div class="form-item">
              <input type="email" placeholder="请输入邮箱" id="email" name="email"
                     class="form-control" required>
            </div>
{#            <div class="form-item">#}
{#              <input type="text" placeholder="请输入图形验证码" id="input_captcha" name="captcha_graph" class="form-captcha">#}
{#              <a href="javascript:void(0);" class="captcha-graph-img">#}
                {#          <img src="../../static/images/captcha.png" alt="验证码" title="点击刷新">#}
{#                <img src="" alt="验证码" title="点击刷新">#}
{#              </a>#}
{#            </div>#}
{#            <div class="form-item">#}
{#              <input type="text" placeholder="请输入邮箱验证码" name="sms_captcha" class="form-captcha" id="input_smscode"#}
{#                     autocomplete="off">#}
{#              <a href="javascript:void(0);" class="sms-captcha" title="发送验证码">获取邮箱验证码</a>#}
{#            </div>#}
            <div class="form-item">
              <input type="submit" value="立即注册" class="register-btn">
            </div>
          </form>
        </div>
      </div>
    </div>
  </article>
{% endblock %}
<!-- container end -->
{% block top %}
{% endblock %}
{% block script %}
{#  <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.js"></script>#}
{#  <script src="{% static 'js/base/common.js' %}"></script>#}
{#  <script src="{% static 'js/base/message.js' %}"></script>#}
{#  <script src="{% static 'js/users/auth.js' %}"></script>#}
{% endblock %}

templates/time.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
</head>
<body>

</body>
</html>